Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.Reservacion.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

apps/Reservacion/urls.py
from django.urls import path, include
from django.conf import settings
from apps.Reservacion import models, views

app_name = 'reservacion'

urlpatterns = [
    path('login/', views.Login.as_view(),name='login3'),
    path('',include('django.contrib.auth.urls'),name='login'),
    path('login2/',views.Login2.as_view(),name='login2'),
    path('index', views.IndexListView.as_view(),name='index'),
    path('detallePaquete/<int:pk>',views.DetallePaqueteDetailView.as_view(), name='detallePaquete'),
    path('conocenos',views.Conocenos.as_view(), name='conocenos'),
    path('contactanos',views.Contactanos.as_view(), name='contactanos'),
    path('misPaquetes',views.MisPaquetesListView.as_view(), name='misPaquetes'),
    path('panelControl',views.PanelControl.as_view(), name='panelControl'),
    path('busqueda', views.Busqueda.as_view(), name='busqueda'),
    path('gestionHotel', views.GestionHotel.as_view(), name='gestionHotel'),
    path('gestionLugar', views.GestionLugar.as_view(), name='gestionLugar'),
    path('gestionPaquete', views.PaqueteListView.as_view(), name='gestionPaquete'),
    path('agencia', views.Agencia.as_view(), name='agencia'),
    path('ofertas', views.OfertasListView.as_view(), name='ofertas'),
    path('registrarReservacion', views.ReservacionCreateView.as_view(), name='registrarReservacion'),
    path('registrarPaquete',views.PaqueteCreateView.as_view(), name='registrarPaquete'),
    path('gestionUsuario',views.UsuarioListView.as_view(), name='gestionUsuario'),
    path('gestionDetallePaquete',views.DetallePaqueteListView.as_view(), name='gestionDetallePaquete'),
    path('registrarUsuario',views.UsuarioCreateView.as_view(), name='registrarUsuario'),
    path('registrarDetallePaquete',views.DetallePaqueteCreateView.as_view(), name='registrarDetallePaquete'),
    path('modificarUsuario/<int:pk>',views.UsuarioUpdateView.as_view(),name='modificarUsuario'),
    path('eliminarUsuario/<int:id>',views.eliminarUsuario,name='eliminarUsuario'),
    path('eliminarDetallePaquete/<int:idDetallePaquete>',views.eliminarDetallePaquete,name='eliminarDetallePaquete'),
    path('eliminarPaquete/<int:id>',views.eliminarPaquete,name='eliminarPaquete'),
    path('modificarPaquete/<int:pk>',views.PaqueteUpdateView.as_view(),name='modificarPaquete'),
    path('modificarDetallePaquete/<int:pk>/',views.DetallePaqueteUpdateView.as_view(),name = 'modificarDetallePaquete'),
    path('registrarCondicion',views.CondicionCreateView.as_view(), name='registrarCondicion'),
    path('upload',views.upload_image_view, name='upload'),
    path('eliminarDetallePaquete/<int:pk>/',views.DetallePaqueteDeleteView.as_view(), name='eliminarDetallePaquete'),
    path('paquetesAll',views.PaquetesAllListView.as_view(), name='paquetesAll'),
    path('recomendacion/',views.Recomendacion.as_view(), name='recomendacion'),
    path('recomendacionPersonalizada',views.RecomendacionPersonalizada.as_view(), name='recomendacionPersonalizada'),
]

    # path('login',include('django.contrib.auth.urls'),name='login'),

apps/Reservacion/views.py
import sys
import os
import csv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from apyori import apriori, load_transactions
from re import split
import json
import itertools
from datetime import datetime
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, CreateView, ListView, DeleteView, UpdateView, DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.db.models import Q, Count
from .forms import *
from .models import *
from .tuplas import *


# Create your views here.

class IndexListView(ListView):
    model : Paquete
    template_name = "page/index.html"
    #context_object_name = 'object_list'
    #queryset = Paquete.objects.filter(estadoPaquete = True)
    def get_queryset(self):
        if str(self.request.user) == 'AnonymousUser':
            lista = []
            #lista de paquetes mas Baratos
            r1 = Paquete.objects.all().values('idPaquete','tituloPaquete', 'precioPaquete', 'disponibilidadPaquete').filter(estadoPaquete= True).order_by('precioPaquete')[:2]
            for obj in r1:
                if  obj['idPaquete'] not in lista:
                    lista.append(obj['idPaquete'])
            
            # lista de paquetes con mejor promedio Score
            r2 = Rating.objects.all().values('paquete_rating','paquete_rating__tituloPaquete','paquete_rating__precioPaquete', 'paquete_rating__idPaquete').filter(estadoRating = True, paquete_rating__estadoPaquete = True).annotate(promedio = models.Sum('scoreRating')/Count('paquete_rating__tituloPaquete')).order_by('-promedio')[:2]
            for obj in r2:
                if  obj['paquete_rating__idPaquete'] not in lista:
                    lista.append(obj['paquete_rating__idPaquete'])
            #lista de paquetes mas visitados
            r3 = Paquete.objects.filter(estadoPaquete = True).order_by('-visitasPaquete')[:2]
            for obj in r3:
                if  obj.idPaquete not in lista:
                    lista.append(obj.idPaquete)
                
            #lista de paquetes mas reservados
            r4 = Reservacion.objects.all().values('paquete_reservacion', 'paquete_reservacion__idPaquete').annotate(total=Count('usuario_Reservacion')).order_by('-total')[:2]
            for obj in r4:
                if  obj['paquete_reservacion__idPaquete'] not in lista:
                    lista.append(obj['paquete_reservacion__idPaquete'])
            #lista de recien añadidos
            r5 = Paquete.objects.filter(estadoPaquete = True).order_by('-fechaCreacionPaquete')[:1]
            for obj in r5:
                if  obj.idPaquete not in lista:
                    lista.append(obj.idPaquete)
            listaPaquetes = Paquete.objects.filter(idPaquete__in = lista)
            return listaPaquetes
        else:
            listaPaquetes = Paquete.objects.none()
            userID = self.request.user.id
            visitados = VisitaUsuario.objects.get(usuario_visitas=userID)
            paquetes = visitados.paquete_visitaUsuario.all()
            if os.path.exists('./dataPackage.csv'):
                with open('C:\\Users\\georg\OneDrive - Universidad Privada del Norte\\_\\Proyecto\\dataPackage.csv', encoding="utf-8") as f:
                    transactions = load_transactions(f, delimiter=",")
                    results = list(apriori(transactions, min_confidence=0.8, min_length=2, min_lift=2.3))
                recomendados = []
                if paquetes.exists():
                    for p in paquetes:
                        for item in results:
                            # first index of the inner list
                            # Contains base item and add item
                            pair = item[0] 
                            items = [x for x in pair]
                            if items[0] == p.tituloPaquete and len(recomendados) <= 9:
                                recomendados.append(items[1])
                                print("Rule: " + items[0] + " -> " + items[1])
                            
                for obj in Paquete.objects.filter(estadoPaquete = True):
                    for t in recomendados:
                        if obj.tituloPaquete == t:
                            listaPaquetes |= Paquete.objects.filter(pk=obj.pk)
            return listaPaquetes
                    
            

        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_rating'] = Form_RegistroRating()
        context['page_title'] = 'Inicio'
        context['loop_times'] = range(1, 6)
        return context
    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty:
            # When pagination is enabled and object_list is a queryset,
            # it's better to do a cheap query than to load the unpaginated
            # queryset in memory.
            if self.get_paginate_by(self.object_list) is not None and hasattr(self.object_list, 'exists'):
                is_empty = not self.object_list.exists()
            else:
                is_empty = not self.object_list
            if is_empty:
                raise Http404(_('Empty list and “%(IndexListView)s.allow_empty” is False.') % {
                    'IndexListView': self.__class__.__name__,
                })
        scoreRating = request.GET.get('scoreRating')
        idPaquete= request.GET.get('idPaquete')
        scores = Rating.objects.filter(estadoRating = True, paquete_rating__estadoPaquete = True, paquete_rating=idPaquete)
        veces = Rating.objects.filter(estadoRating = True, paquete_rating__estadoPaquete = True, paquete_rating=idPaquete).count()
        suma = 0
        for score in scores:
            if score is not None:
                suma = score.scoreRating
            else:
                pass
        print(veces)
        if veces != 0 :
            suma = suma/veces
        else:
            suma = suma
        idPaquete= request.GET.get('idPaquete')
        if scoreRating and idPaquete:
            obj = Paquete.objects.get(idPaquete = idPaquete)
            obj = Rating.objects.create(scoreRating=scoreRating, paquete_rating=obj)
            obj.save()
        return self.render_to_response(self.get_context_data(suma=suma))

# class RatingTemplateView(JSONFormMixin, TemplateView):
#     form_class = Form_RegistroRating


class PaquetesAllListView(ListView):
    model = Paquete
    template_name = "page/paquetesAll.html"
    queryset = Paquete.objects.filter(estadoPaquete= True, disponibilidadPaquete__gte = 1).order_by('-fechaCreacionPaquete')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total'] = Paquete.objects.filter(estadoPaquete= True, disponibilidadPaquete__gte = 1).order_by('-fechaCreacionPaquete').count()
        context["page_title"] = "Todos Los Paquetes Disponibles"
        return context
    



class DetallePaqueteDetailView(DetailView):
    template_name = "page/detallePaquete.html"
    model = Paquete

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.request.session['paqueteID'] = self.object.pk
        obj = Paquete.objects.get(idPaquete=self.object.pk)
        num_visits =  obj.visitasPaquete #self.request.session.get('num_visits', 0)
        self.request.session['num_visits'] = num_visits + 1
        Paquete.objects.filter(idPaquete=self.object.pk).update(visitasPaquete=self.request.session['num_visits'])
        if not(str(self.request.user) == 'AnonymousUser'):
            visita = VisitaUsuario.objects.get(usuario_visitas=self.request.user.id)
            paquetes = visita.paquete_visitaUsuario.all()
            if paquetes.exists():
                for p in paquetes:
                    if obj.idPaquete == p.idPaquete:
                        break
                    else:
                        visita.paquete_visitaUsuario.add(obj)
            else:
                visita.paquete_visitaUsuario.add(obj)
        context['listaDetalles'] = DetallePaquete.objects.filter(paquete_detallePaquete = self.object.pk)
        context['page_title'] = 'Detalle del Paquete'
        context['condiciones'] = obj.condicion_paquete.all()
        noCondiciones = Condicion.objects.none()
        for c in Condicion.objects.all():
            band = False
            for n in context['condiciones']:
                if c.idCondicion == n.idCondicion:
                    band = True
                    break
            if not(band):
                noCondiciones |= Condicion.objects.filter(pk=c.pk)
        context['noCondiciones'] = noCondiciones
        
        # try:
        #     persona = Persona.objects.get(ci="12345678901")
        # except Persona.DoesNotExist:
        #     # entrará aqui cuando no exista ningun elemento
        #     # que coincida con la busqueda
        #     pass
        # except Persona.MultipleObjectsReturned:
        #     # entrará aqui cuando se haya encontrado más de un
        #     # objeto que coincida
        #     pass
        # through_model = VisitaUsuario.paquete_visitaUsuario.through
        # through_model.objects.bulk_create([
        #     through_model(photo_id=pk, photostream_id=for_classmates.pk) 
        #         for pk in childhood_photos.values_list('pk', flat=True)
        # ])
        return context

class Conocenos(TemplateView):
    template_name = "page/conocenos.html"


class Contactanos(TemplateView):

apps/Reservacion/templates/page/calificacionPaquete.html
<div id="calificacion" >
    <h1>Calificación</h1>
    <!-- {{form}} -->
</div>

apps/Reservacion/templates/page/masterPage.html
<!--Source  Media Root and Media URL: http://blog.enriqueoriol.com/2014/07/upload-de-imagenes-con-django.html -->
<!DOCTYPE html>
<html lang="es">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>
    {% block title %}
        Bienvenidos
    {% endblock title %}
     </title>   
     <script src="https://kit.fontawesome.com/c7760fb283.js" crossorigin="anonymous"></script>

    <!-- core CSS -->
    <link href="{% static 'corlate/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href=" {% static 'corlate/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href=" {% static 'corlate/css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'corlate/css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'corlate/css/owl.carousel.min.css' %} " rel="stylesheet">
    <link href="{% static 'corlate/css/icomoon.css' %} " rel="stylesheet">
    <link href="{% static 'corlate/css/main.css' %} " rel="stylesheet">
    <link href="{% static 'corlate/css/responsive.css' %} " rel="stylesheet">
    <link href="{% static 'corlate/css/mycss.css' %} " rel="stylesheet">
    <link href="{% static 'corlate/css/css_ribbon.css' %} " rel="stylesheet">
    <!-- StarRating -->
    
    
        
    
    <!-- <link rel="stylesheet" href="{% static 'StarRating/css/bootstrap.min.css' %} "> -->
        
    <!-- <link href="{% static 'corlate/css1/bootstrap.min.css' %} " rel="stylesheet"> -->
    <!-- <link href="{% static 'corlate/css1/font-awesome.min.css' %} " rel="stylesheet"> -->
    <link href="{% static 'corlate/css1/style.css' %} " rel="stylesheet">
    <!-- <link href="{% static 'corlate/css1/animate.css' %} " rel="stylesheet"> -->
    <!-- <link href="{% static 'corlate/css1/skin-blue.css' %} " rel="stylesheet"> -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{% static 'img/main.ico' %} ">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'corlate/images/ico/apple-touch-icon-144-precomposed.png' %} ">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href=" {% static 'corlate/images/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'corlate/images/ico/apple-touch-icon-72-precomposed.png' %} ">
    <link rel="apple-touch-icon-precomposed" href="{% static 'corlate/images/ico/apple-touch-icon-57-precomposed.png' %} ">
    <!-- Font Awesome Icon Library -ESTRELLAS DE RATING -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"/>
    

</head>
<!--/head-->

<body class="homepage">
    <header id="header">
        

        <nav class="navbar navbar-inverse" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'reservacion:index' %}"><img style="width:100px; height:60px;" src=" {% static 'img/Logogrande_.perutogethertravel.png' %} " alt="logo"></a>
                </div>

                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="{% if request.path == '/index' %}active {% endif %}"><a href="{% url 'reservacion:index' %}">Inicio</a></li>
                        <li class="{% if request.path == '/ofertas' %}active {% endif %}"><a href="{% url 'reservacion:ofertas' %}">Ofertas</a></li>
                        <li class="{% if request.path == '/agencia' %}active {% endif %}"><a href="{% url 'reservacion:agencia' %}">Agencia</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Nosotros <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'reservacion:conocenos' %}">Conócenos</a></li>
                                <li><a href="{% url 'reservacion:contactanos' %}">Contáctanos</a></li>
                            </ul>
                        </li>
                        
                        {% if user.is_authenticated %}
                            <li class="{% if request.path == '/misPaquetes' %}active {% endif %}"><a href="{% url 'reservacion:misPaquetes' %}">Mis Paquetes</a></li>  
                        {% else %}
                            <li class="{% if request.path == '/login' %}active {% endif %}"><a href="{% url 'reservacion:login3' %}">Inicio de Sesion</a></li>
                        {% endif %}
                        
                        {% if user.is_authenticated and  user.is_staff == True %}
                            <li class="{% if request.path == '/panelControl' %}active {% endif %}"><a href="{% url 'reservacion:panelControl' %}">Panel de Control</a></li>
                        {% endif %}
                        {% if user.is_authenticated%}
                            <li class=""><a href="{% url 'reservacion:logout' %} "><i class="fas fa-power-off"></i></a></li>
                        {% endif %}
                        
                    </ul>
                </div>
            </div>
            <!--/.container-->
        </nav>
        <!--/nav-->

    </header>
    <!--/header-->

    
    {% block content %}
        
    {% endblock content %}
    <section id="bottom">
        <div class="container fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
            <div class="row">
                <div class="col-md-2">
                    <a href="#" class="footer-logo">
                        <img src="{% static 'img/Logogrande_.perutogethertravel.png' %} " alt="logo">
                    </a>
                </div>
                <div class="col-md-10">
                    <div class="row">
                        <div class="col-md-3 col-sm-6">
                            <div class="widget">
                                <h3>Empresa</h3>
                                <ul>
                                    <li><a href="{% url 'reservacion:conocenos' %}">Conócenos</a></li>
                                    <li><a href="#">Políticas de privacidad</a></li>
                                    <li><a href="#">Contáctanos</a></li>
                                </ul>
                            </div>
                        </div>
                        <!--/.col-md-3-->

                        <div class="col-md-3 col-sm-6">
                            <div class="widget">
                                <h3>Nuestros convenios</h3>
                                <ul>
                                    <li><a href="https://www.zankyou.com.pe/f/jh-travel-613731">JH Travel</a></li>
                                    <li><a href="https://www.zankyou.com.pe/f/trujillo-travel-610146">Trujillo Travel</a></li>
                                    <li><a href="https://www.zankyou.com.pe/f/gilberth-tours-661426">Gilberth Tours</a></li>
                                    <li><a href="https://www.zankyou.com.pe/f/contunor-661429">Contunor</a></li>
                                    <li><a href="https://www.zankyou.com.pe/f/travelers-tours-peru-401003">Travelers Tours Perú</a></li>
                                    <li><a href="https://www.zankyou.com.pe/f/trujillo-tours-661431">Trujillo Tours</a></li>
                                    <li><a href="https://www.zankyou.com.pe/f/peru-costa-travel-661432">Perú Costa Travel</a></li>
                                    <li><a href="https://www.zankyou.com.pe/f/north-peru-tours-602960">North Peru Tours</a></li>
                                    <li><a href="https://www.zankyou.com.pe/f/peru-travel-tour-operador-661866">Perú Travel – Tour Operador</a></li>
                                    <li><a href="https://www.zankyou.com.pe/f/ittsa-bus-661439">Ittsa Bus</a></li>
                                </ul>
                            </div>
                        </div>
                        <!--/.col-md-3-->
                    </div>
                </div>


            </div>
        </div>
    </section>
    <!--/#bottom-->
    
    <footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                
    
                <div class="col-sm-6">
                    &copy; 2020 <a target="_blank" href="http://wwww.facebook.com" title="Pagina Oficial de Facebook"> <strong>UPN - Prueba</strong></a> con Derechos Reservados
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                        <li><a href="{% url 'reservacion:index' %}">Inicio</a></li>
                        <li><a href="{% url 'reservacion:agencia' %}">Agencia</a></li>
                        <li><a href="{% url 'reservacion:conocenos' %}">Conócenos</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'reservacion:misPaquetes' %}">Mis Paquetes</a></li>
                        
                    
                    {% else %}
                        <li><a href="{% url 'reservacion:login' %}">Iniciar Sesion</a></li>
                    {% endif %}

                    
                    {% if user.is_authenticated and user.is_staff == True %}
                        <li><a href="{% url 'reservacion:panelControl' %}">Panel de Control</a></li>
                    {% endif %}
                     
                            
                        
                    </ul>
                </div>
                <br>
                <p>
                    <div class="col-sm-6 col-xs-12">
                        <div class="top-number">
                            <p><i class="fa fa-phone-square"></i>1-978282606 / 948494066</p> 
                        </div>
                    </div>
                    <div class="col-sm-6 col-xs-12">
                        <div class="social">
                            <ul class="social-share">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-skype"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </p>
                
            </div>
        </div>
    </footer>
    
        
    <!--/#footer-->
    <script src="{% static 'corlate/js/jquery.js' %}"></script>
    <script src="{% static 'corlate/js/bootstrap.min.js' %} "></script>
    <script src="{% static 'corlate/js/jquery.prettyPhoto.js' %} "></script>
    <script src="{% static 'corlate/js/owl.carousel.min.js' %} "></script>
    <script src="{% static 'corlate/js/jquery.isotope.min.js' %} "></script>
    <script src="{% static 'corlate/js/main.js' %} "></script>
    <script src="{% static 'corlate/js/myscript.js' %} "></script>
    <!-- starr -->
    <!-- Mi propio Script -->
    <script src="{% static 'AdminLTE/dist/js/myscript.js' %} "></script>
    {% block scripts %}
        
    {% endblock scripts %}
    
</body>

</html>

apps/Reservacion/templates/page/ofertas.html
{% extends 'page/masterPage.html' %}

{% load static %}


{% block title %}
    {{page_title}}
{% endblock title %}
    

{% block content %}

<div class="page-title" style="background-image: url('static/corlate/images/portfolio/fondo2.jpg')">
    <h1>Disfruta de las mejores ofertas {{user.first_name}} {{user.last_name}}</h1>  
</div>
<section id="team-area">
    <div class="container">
        <div class="row">            
            {% if object_list %}
                {% for obj in object_list %}
                <div class="col-md-4 col-sm-6 single-team">
                    <div class="inner">
                        {% if obj.ofertaPaquete == True %}
                            <div class="box">
                                <div class="ribbon ribbon-top-left"><span>Oferta</span></div>
                                <div class="ribbon ribbon-top-right"><span>Oferta</span></div>
                                <!-- <div class="ribbon ribbon-bottom-left"><span>ribbon</span></div>
                                <div class="ribbon ribbon-bottom-right"><span>ribbon</span></div> -->
                            </div>
                        {% endif %}
                        <div class="team-img">
                            <!-- <a href="{% url 'reservacion:registrarReservacion' %}"><img src="https://www.perutogethertravel.com/wp-content/uploads/2019/06/FIESTAS-PATRIAS-CHACHAPOYAS1-700x466.jpg" alt=""></a>  -->
                            <a href="{% url 'reservacion:registrarReservacion' %}"><img src="{{ obj.get_imageAvatar }}" alt=""></a>
                        </div>
                        <div class="team-content">
                            <h4></h4>
                            <span class="desg"><strong>{{obj.tituloPaquete}}</strong> </span>
                            <br>
                            <span class="desg">{{obj.nDiasPaquete}} Días</span>
                            <br/>
                            <p><span class="desg"> <h1><strong>{{obj.precioPaquete}} </strong></h1> </span></p>
                            <div class="clearfix text-center">
                                <a href="{% url 'reservacion:detallePaquete' obj.pk %}" class="btn btn-primary">Ver Detalle</a>
                                <a class="btn btn-primary" href="{% url 'reservacion:login' %}">Regístrate</a>
                            </div>
                            <h2>Calificación</h2>

                            {% for i in loop_times %}
                                <span class="fa fa-star checked"></span>
                            {% endfor %}
                            
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <p>No Existe Ofertas Disponibles</p>
            {% endif %}
        </div>
    </div>
</section>
{% endblock content %}
    

apps/Reservacion/templates/page/paquetesAll.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title">{{page_title}} | Total: {{total}} paquetes</h2>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="row">            
            {% if object_list %}
                {% for obj in object_list %}
                <div class="col-md-4 col-sm-6 single-team">
                    <div class="inner">
                        <div class="team-img">
                            <!-- <a href="{% url 'reservacion:registrarReservacion' %}"><img src="https://www.perutogethertravel.com/wp-content/uploads/2019/06/FIESTAS-PATRIAS-CHACHAPOYAS1-700x466.jpg" alt=""></a>  -->
                            <img src="{{ obj.get_imageAvatar }}" alt="{{ obj.tituloPaquete }}">
                        </div>
                        <div class="team-content">
                            <h4></h4>
                            <span class="desg"><strong>{{obj.tituloPaquete}}</strong> </span>
                            <br>
                            <span class="desg">{{obj.nDiasPaquete}} Días</span>
                            <br/>
                            <p><span class="desg"> <h1><strong>{{obj.precioPaquete}} </strong></h1> </span></p>
                            <div class="clearfix text-center">
                                <a href="{% url 'reservacion:detallePaquete' obj.pk %}" class="btn btn-primary">Ver Detalle</a>
                                <a class="btn btn-primary" href="{% url 'reservacion:login' %}">Regístrate</a>
                            </div>
                            <h2>Calificación</h2>

                            {% for i in loop_times %}
                                <span class="fa fa-star checked"></span>
                            {% endfor %}
                            
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <p>No Existe Ofertas Disponibles</p>
            {% endif %}
        </div>
    </div>
</div>