Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.Reservacion.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

apps/Reservacion/urls.py
from django.urls import path, include
from django.conf import settings
from apps.Reservacion import models, views

app_name = 'reservacion'

urlpatterns = [
    path('login/', views.Login.as_view(),name='login3'),
    path('',include('django.contrib.auth.urls'),name='login'),
    path('login2/',views.Login2.as_view(),name='login2'),
    path('index', views.IndexListView.as_view(),name='index'),
    path('detallePaquete/<int:pk>',views.DetallePaqueteDetailView.as_view(), name='detallePaquete'),
    path('conocenos',views.Conocenos.as_view(), name='conocenos'),
    path('contactanos',views.Contactanos.as_view(), name='contactanos'),
    path('misPaquetes',views.MisPaquetesListView.as_view(), name='misPaquetes'),
    path('panelControl',views.PanelControl.as_view(), name='panelControl'),
    path('busqueda', views.Busqueda.as_view(), name='busqueda'),
    path('gestionHotel', views.GestionHotel.as_view(), name='gestionHotel'),
    path('gestionLugar', views.GestionLugar.as_view(), name='gestionLugar'),
    path('gestionPaquete', views.PaqueteListView.as_view(), name='gestionPaquete'),
    path('agencia', views.Agencia.as_view(), name='agencia'),
    path('ofertas', views.OfertasListView.as_view(), name='ofertas'),
    path('registrarReservacion', views.ReservacionCreateView.as_view(), name='registrarReservacion'),
    path('registrarPaquete',views.PaqueteCreateView.as_view(), name='registrarPaquete'),
    path('gestionUsuario',views.UsuarioListView.as_view(), name='gestionUsuario'),
    path('gestionDetallePaquete',views.DetallePaqueteListView.as_view(), name='gestionDetallePaquete'),
    path('registrarUsuario',views.UsuarioCreateView.as_view(), name='registrarUsuario'),
    path('registrarDetallePaquete',views.DetallePaqueteCreateView.as_view(), name='registrarDetallePaquete'),
    path('modificarUsuario/<int:pk>',views.UsuarioUpdateView.as_view(),name='modificarUsuario'),
    path('eliminarUsuario/<int:id>',views.eliminarUsuario,name='eliminarUsuario'),
    path('eliminarDetallePaquete/<int:idDetallePaquete>',views.eliminarDetallePaquete,name='eliminarDetallePaquete'),
    path('eliminarPaquete/<int:id>',views.eliminarPaquete,name='eliminarPaquete'),
    path('modificarPaquete/<int:pk>',views.PaqueteUpdateView.as_view(),name='modificarPaquete'),
    path('modificarDetallePaquete/<int:pk>/',views.DetallePaqueteUpdateView.as_view(),name = 'modificarDetallePaquete'),
    path('registrarCondicion',views.CondicionCreateView.as_view(), name='registrarCondicion'),
    path('upload',views.upload_image_view, name='upload'),
    path('eliminarDetallePaquete/<int:pk>/',views.DetallePaqueteDeleteView.as_view(), name='eliminarDetallePaquete'),
    path('paquetesAll',views.PaquetesAllListView.as_view(), name='paquetesAll'),
    path('recomendacion/',views.Recomendacion.as_view(), name='recomendacion'),
    path('recomendacionPersonalizada',views.RecomendacionPersonalizada.as_view(), name='recomendacionPersonalizada'),
]

    # path('login',include('django.contrib.auth.urls'),name='login'),

apps/Reservacion/models.py
from django.db import models, transaction
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from apps.Reservacion.tuplas import *
from django.urls import reverse
#from django_google_maps import fields as map_fields 
# Create your models here.

# class Rental(models.Model):
#     address = map_fields.AddressField(max_length=200)
#     geolocation = map_fields.GeoLocationField(max_length=100)
class Mes(models.Model):
    idMes = models.AutoField(primary_key=True, help_text="ID único para esta Mes")
    tituloMes = models.CharField(verbose_name='Nombre' ,max_length=200, help_text='')
    # fechaCreacionMes = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')
    estadoMes = models.BooleanField(verbose_name='Activo', default=True)

    def __str__(self):
        return str(self.tituloMes)


class Usuario(AbstractUser):
    imagenUsuario = models.ImageField(verbose_name='Imagen de Perfil', upload_to='img/users/', blank=True, null=True)
    DNIUsuario = models.CharField(max_length=20,verbose_name='Doc. Identidad', help_text='')
    telefonoUsuario = models.CharField(max_length=20, verbose_name='Telefono', help_text='No incluya Parentesis, ni guiones ni espacios')
    # paquete_usuario = models.ManyToManyField(Paquete, verbose_name = 'Paquete Calificado', related_name='PaqueteCalificadoPorUsuario')
    class Meta: 
        """Meta definition for Paquete."""

        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'
    
    def __str__(self):
        return self.username

    def get_image(self):
        if self.imagenUsuario:
            return '{}{}'.format(settings.MEDIA_URL, self.imagenUsuario)
        return '{}{}'.format(settings.STATIC_URL,'img/users/empty.png')


class Hotel(models.Model):
    idHotel = models.AutoField(primary_key=True, help_text="ID único para Hotel")
    nombreHotel = models.DateTimeField(verbose_name='Nombre', help_text="nombre de Hotel donde se hospedará")
    ciudadHotel = models.DateTimeField(verbose_name='Ciudad', help_text="nombre de la ciudad del Hotel")
    telefonoHotel = models.DateTimeField(verbose_name='Telefono', help_text="ID único para Hotel")
    estadoVuelo = models.BooleanField(verbose_name='estado', default=True)

    class Meta:
        ordering = ["idHotel"]

    def __str__(self):
        return self.idHotel


class Vuelo(models.Model):
    idVuelo = models.AutoField(primary_key=True, help_text="ID único para Vuelo")
    origenVuelo = models.TextField(max_length=500, verbose_name='Origen')
    destinoVuelo = models.TextField(max_length=500, verbose_name='Destino')
    fechaVuelo = models.DateTimeField(verbose_name='Fecha de Vuelo', auto_now_add=True)
    estadoVuelo = models.BooleanField(verbose_name='Activo', default=True)

    class Meta:
        ordering = ["idVuelo"]

    def __str__(self):
        return self.idVuelo

class VueloTurista(models.Model):
    idVueloTurista = models.AutoField(primary_key=True, help_text="ID único para Vuelo Turista")
    descripcion_vueloTurista = models.TextField(max_length=500, verbose_name='Descripcion de Vuelo')
    vuelo_vueloTurista = models.ForeignKey(Vuelo, on_delete=models.SET_NULL, null=True)
    estadoVueloTurista = models.BooleanField(verbose_name='Activo', default=True)

    class Meta:
        ordering = ["idVueloTurista"]

    def __str__(self):
        return self.idVueloTurista

# class ViajeContratado(models.Model):
#     idViajeContratado = models.AutoField(primary_key=True, help_text="ID único para Viaje contratado")
#     reservacion_viajeContratado = models.ForeignKey(Reservacion, on_delete=models.SET_NULL, null=True)
#     usuario_viajeContratado = models.ForeignKey(Usuario, on_delete=models.SET_NULL, null=True)
#     vueloTurista_vueloContratado = models.ForeignKey(VueloTurista, on_delete=models.SET_NULL, null= True)
#     estadoViajeContratado = models.BooleanField(verbose_name='Activo', default=True)

#     class Meta:
#         ordering = ["idViajeContratado"]

#     def __str__(self):
#         return self.reservacion_viajeContratado
class Condicion(models.Model):
    """Model definition for CondicionPaquete."""

    idCondicion = models.AutoField(verbose_name="ID CONDICION PAQUETE", primary_key=True, help_text='ID unico')
    
    tituloCondicion = models.CharField(verbose_name="Tipo de Condicion", max_length=250, help_text='', null=True, blank=True)
    tipoCondicion = models.CharField(verbose_name="Tipo de Condicion", max_length=1, choices=CONDICIONPAQUETE, help_text='', null=True, blank=True)
    descripcionCondicion = models.TextField(verbose_name="Descripcion de la condicion", max_length=1000, null=True, blank=True, help_text='')
    #paquete_condicion = models.ForeignKey(Paquete, verbose_name="Condiciones", help_text="" ,on_delete=models.SET_NULL , null=True, blank=True)
    estadoCondicion = models.BooleanField(verbose_name='Es Activo',default=True)
    
    class Meta:
        """Meta definition for CondicionPaquete."""

        verbose_name = 'CondicionPaquete'
        verbose_name_plural = 'CondicionPaquetes'

    def __str__(self):
        return self.descripcionCondicion


class Paquete(models.Model):
    """Paquete Turistico."""
    idPaquete  = models.AutoField(primary_key=True, help_text="ID único para este Paquete")
    tituloPaquete = models.CharField(max_length=250,verbose_name='titulo del paquete' , blank=True, null=True, unique=True)
    nDiasPaquete = models.CharField(verbose_name='Cantidad de días', max_length=2, choices=CANTIDAD, blank=True, default='0', help_text='')
    nNochesPaquete = models.CharField(verbose_name='Cantidad de noches', max_length=2, choices=CANTIDAD, blank=True, default='0', help_text='')
    nHorasPaquete = models.CharField(verbose_name='Cantidad de Horas', max_length=2, choices=HORAS, blank=True, default='0', help_text='')
    tipoMonedaPaquete = models.CharField(verbose_name='Tipo de moneda', max_length=1, choices=MONEDA, blank=True, default='s', help_text='Un solo Dia')
    precioPaquete = models.DecimalField(verbose_name='Precio',help_text='Precio en soles o dólares',max_digits=8, decimal_places=2, blank=True, null=True, default=500.00)
    unidadPorPrecioPaquete = models.CharField(verbose_name='Unidad por precio', max_length=1, choices=UNIDADPORPAGO, blank=True, null=True, default='p', help_text='')
    edadMinimaPaquete = models.PositiveIntegerField(default=5, validators=[MinValueValidator(1), MaxValueValidator(18)], blank=True, null=True,help_text='')
    visitasPaquete = models.PositiveIntegerField(verbose_name='Visitas',help_text='', blank=True, null=True, default=0)
    mesPaquete = models.CharField(verbose_name='Mes de Disponiblidad', max_length=15, choices=MESES, null=True,blank=True, default='Todos los meses', help_text='')
    mes_paquete = models.ManyToManyField(Mes, verbose_name="Meses", help_text="")
    disponibilidadPaquete = models.PositiveIntegerField(verbose_name='Numero de Cupos', null=True,blank=True, help_text='', default=150, validators=[MinValueValidator(0), MaxValueValidator(150)])
    imagenPrincipal = models.ImageField(verbose_name='Imagen de Fondo', upload_to='img/paquetes/', blank=True, null=True)
    imagenAvatar = models.ImageField(verbose_name='Imagen Pequeña', upload_to='img/paquetes/', blank=True, null=True)
    fechaCreacionPaquete = models.DateTimeField(verbose_name='Fecha de Registro', auto_now_add=True , blank=True, null=True)
    ofertaPaquete = models.BooleanField(verbose_name='Oferta', default=True,null=True, blank=True)
    condicion_paquete = models.ManyToManyField(Condicion, verbose_name="Condiciones", help_text="")
    estadoPaquete = models.BooleanField(verbose_name='Activo', default=True, null=True, blank=True)
    class Meta: 
        """Meta definition for Paquete."""

        verbose_name = 'Paquete'
        verbose_name_plural = 'Paquetes'

    def __str__(self):
        return str(self.tituloPaquete)
    def get_imageAvatar(self):
        if self.imagenAvatar:
            return '{}{}'.format(settings.MEDIA_URL, self.imagenAvatar)
        return '{}{}'.format(settings.STATIC_URL,'img/paquetes/empty.png')
    def get_imagePaquete(self):
        if self.imagenPrincipal:
            return '{}{}'.format(settings.MEDIA_URL, self.imagenPrincipal)
        return '{}{}'.format(settings.STATIC_URL,'img/paquetes/empty.png')
    def get_precioAntiguo(self):
        """
        Traer el Precio anterior
        """
        return self.precioPaquete+100


class DetallePaquete(models.Model):
    idDetallePaquete  = models.AutoField(primary_key=True, help_text="ID único para este Paquete")
    tituloDetallePaquete = models.CharField(max_length=250,verbose_name='titulo del paquete' , blank=True, null=True)
    nroDiaDetallePaquete = models.PositiveSmallIntegerField(verbose_name='Numero de Dia', null=True,help_text='', default=1)
    paquete_detallePaquete = models.ForeignKey(Paquete,on_delete=models.SET_NULL , null=True, blank=True)
    descripcionDetallePaquete = models.TextField(verbose_name='Descripcion', max_length=2000, null=True, blank=True)
    imagenDetallePaquete = models.ImageField(verbose_name='Imagen', upload_to='img/detallePaquete/', blank=True, null=True)
    estadoDetallePaquete = models.BooleanField(verbose_name='Es Activo',default=True)
    class Meta: 
        """Meta definition for Paquete."""

        verbose_name = 'Detalle del Paquete'
        verbose_name_plural = 'Detalles del Paquete'

    def get_imagenDetallePaquete(self):
        if self.imagenDetallePaquete:
            return '{}{}'.format(settings.MEDIA_URL, self.imagenDetallePaquete)
        return '{}{}'.format(settings.STATIC_URL,'img/paquetes/empty.png')
    def __str__(self,):
        return str(self.nroDiaDetallePaquete)


class Reservacion(models.Model):
    idReservacion = models.AutoField(primary_key=True, help_text="ID único para esta Reservacion")

apps/Reservacion/templates/management/masterPage.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> 
    {% block title %}
      Sistema de Reservación de Paquetes Turisticos
    {% endblock title %}
  </title>
  {% load static %}
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'AdminLTE/plugins/fontawesome-free/css/all.min.css' %} ">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %} ">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %} ">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'AdminLTE/plugins/jqvmap/jqvmap.min.css' %} ">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'AdminLTE/dist/css/adminlte.min.css' %} ">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %} ">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'AdminLTE/plugins/daterangepicker/daterangepicker.css' %} ">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'AdminLTE/plugins/summernote/summernote-bs4.min.css' %} ">
  
  <link rel="shortcut icon" href="{% static 'img/icono.ico' %} ">


</head>
<body class="hold-transition sidebar-mini layout-fixed">

<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      
      {% block superior %}
        
      {% endblock superior %}
    
    
    
      
    

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{user.get_image}}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  {{request.user.first_name}}
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="{% url 'reservacion:logout' %}" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  CERRAR SESION
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{% static 'img/Logogrande_.perutogethertravel.png ' %} " alt="Logo de Empresa" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Panel</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          
          <!-- {% if request.user.get_image %} -->
            <img src="{{ request.user.get_image }}" class="img-circle elevation-2" alt="Imagen Usuario">
          <!-- {% else %} -->
            <!-- <img src="{% static 'img/empty.jpg' %{{user.imagenUsuario.url}}}" class="img-circle elevation-2" alt="Imagen Usuario"> -->
          <!-- {% endif %} -->
            
          
          <!-- <img src="/media/{{ user.imagenUsuario }}" class="img-circle elevation-2" alt="Imagen Usuario">  -->
        </div>
        <div class="info">
          <a href="#" class="d-block">{{user.first_name}} {{user.last_name}} </a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
               <li class="nav-item {% if request.path == '/index' %}active {% endif %}">
                <a href="{% url 'reservacion:index' %}" class="nav-link {% if request.path == '/index' %}active {% endif %}">
                  <i class="nav-icon fas fa-th"></i>
                  <p>
                    Pagina de Inicio
                    <span class="right badge badge-danger">Principal</span>
                  </p>
                </a>
              </li>
              <li class="nav-item {% if request.path == '/busqueda' %}active {% endif %}">
                <a href="{% url 'reservacion:busqueda' %}" class="nav-link {% if request.path == '/busqueda' %}active {% endif %}">
                  <i class="nav-icon far fa-image"></i>
                  <p>
                    Busqueda
                  </p>
                </a>
              </li>
              <li class="nav-item {% if request.path == '/gestionUsuario' %}active {% endif %}">
                <a href="{% url 'reservacion:gestionUsuario' %}" class="nav-link {% if request.path == '/gestionUsuario' %}active {% endif %}">
                  <i class="nav-icon far fa-user"></i>
                  <p>
                    Usuario
                  </p>
                </a>
              </li>
              <li class="nav-item {% if request.path == '/gestionPaquete' %}active {% endif %}">
                <a href="{% url 'reservacion:gestionPaquete' %}" class="nav-link {% if request.path == '/gestionPaquete' %}active {% endif %}">
                  <i class="nav-icon far fa-image"></i>
                  <p>
                    Paquetes Turisticos
                  </p>
                </a>
              </li>
              <li class="nav-item {% if request.path == '/recomendacion' %}active {% endif %}">
                <a href="{% url 'reservacion:recomendacion' %} " class="nav-link {% if request.path == '/recomendacion' %}active {% endif %}">
                  <i class="nav-icon far fa-image"></i>
                  <p>
                    RECOMENDACION
                  </p>
                </a>
              </li>
              <li class="nav-item {% if request.path == '/recomendacionPersonalizada' %}active {% endif %}">
                <a href="{% url 'reservacion:recomendacionPersonalizada' %} " class="nav-link {% if request.path == '/recomendacionPersonalizada' %}active {% endif %}">
                  <i class="nav-icon far fa-image"></i>
                  <p>
                    RECOMENDACION PERSONAL
                  </p>
                </a>
              </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    {% block jumbotron %}
    {% endblock %}
    {% block content %}
        
    {% endblock content %}
        
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2020 <a href="http://www.Facebook.com">UPN - Prueba</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 1.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'AdminLTE/plugins/jquery/jquery.min.js' %} "></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'AdminLTE/plugins/jquery-ui/jquery-ui.min.js' %} "></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
<!-- ChartJS -->
<script src="{% static 'AdminLTE/plugins/chart.js/Chart.min.js' %} "></script>
<!-- Sparkline -->
<script src="{% static 'AdminLTE/plugins/sparklines/sparkline.js' %} "></script>
<!-- JQVMap -->
<script src="{% static 'AdminLTE/plugins/jqvmap/jquery.vmap.min.js' %} "></script>
<script src="{% static 'AdminLTE/plugins/jqvmap/maps/jquery.vmap.usa.js' %} "></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'AdminLTE/plugins/jquery-knob/jquery.knob.min.js' %} "></script>
<!-- daterangepicker -->
<script src="{% static 'AdminLTE/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'AdminLTE/plugins/daterangepicker/daterangepicker.js' %} "></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'AdminLTE/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %} "></script>
<!-- Summernote -->
<script src="{% static 'AdminLTE/plugins/summernote/summernote-bs4.min.js' %} "></script>
<!-- overlayScrollbars -->
<script src="{% static 'AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %} "></script>
<!-- AdminLTE App -->
<script src="{% static 'AdminLTE/dist/js/adminlte.js' %} "></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'AdminLTE/dist/js/demo.js' %} "></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'AdminLTE/dist/js/pages/dashboard.js' %} "></script>
<!-- Mi propio Script -->
<script src="{% static 'AdminLTE/dist/js/myscript.js' %} "></script>


{% block scripts %}
  
{% endblock scripts %}
  
</body>
</html>